version: '3.7'

services:
  mysql:
    platform: linux/x86_64
    container_name: test-mysql
    image: mysql:latest
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/db

  redis:
    container_name: test-redis
    image: redis:latest
    ports:
      - 6379:6379
volumes:
  mysql-data:
